### ISSUE TITLE
试了下 Demo，发现每次加载下一页都会发出两次请求

### ISSUE THREAD

**Issue by jerrybendy** [Yuyz0112/vue-loadmore-demo#1]
![image](https://cloud.githubusercontent.com/assets/7897384/15696405/97f303fc-27e2-11e6-94d5-db2faf9777ba.png)

**Comment by Yuyz0112** [comment]
@jerrybendy 因为ajax请求是用的reqwest这个第三方库，请求的目标地址是cnode社区的API，属于跨域请求，所以在请求的设置中添加了crossOrigin的选项。reqwest在处理跨域请求的时候，会先发一个Request Method为OPTIONS的请求以获得更多对方信息，再根据对方服务器支持情况选择使用哪种方式进行实际的请求。
对比看一下两个请求的request和response应该可以看到。
